### ISSUE TITLE
Guest Registration

### ISSUE THREAD

**Issue by walt0019** [SFDO-Community/Summit-Events-App#226]
At our university, we host (virtually now) events where a person/organization could purchase a table and has multiple seats (registrations) to the event. Another similar use case is a high school counselor is bringing multiple students from their school to visit campus. In both use cases, the actions of the person registering is similar.

* Person wants to sign up for a block of registrations (guest registrations) for an event.
* The Guest registrations should tie to the person requesting the registrations.
* The person may have all the Guest registration names at time of initial registration and wants to provide information like First Name, Last Name, Email Address.
* But there are cases where the person just wants to secure the Guest registrations and come back to provide contact details later. The person may not know who is attending yet or required information. The person should be able to come back to their registration page without logging back in (link). Registration placeholders records should be created in this scenario so accurate counts are collected.
* The Guest registrations records should be created for each Guest and treated similar to an individual registration records.
* Guest registrations should be tied to Contact records, following processes for matching/creating Contacts in Salesforce like standard Summit Events registrations.
* Guests should receive event email reminders like individual registration, but also with information on how the registration was created.
* Reporting is available for Registrations as a whole or separated by guest groupings.
* In some cases there are payments to be able to register guests and in other cases registration is free. I wanted to call it out, but acknowledge we have had separate conversation on payment solutions.
* Optionally return to provide guest names later (configurable to be required at checkout)
* Have "table/fee types" at the instance level with a table size (max # guests) and an adjustable inventory count (max registrations of that type). "fee type" registrations can't exceed inventory level.
* Allow for open seating scenarios (individual tickets purchased together - all names required at checkout, but single checkout) in combination with reserved tables, with an inventory level for open seating.
* Turn off "table/fee types" registration separately (could be accomplished by adjusting inventory capacity to currently registered count, but a checkbox or status field would be nice)
* Checkout once with more than one table and individual seats for open seating tables -- or allow multiple "passes" through simple checkout process with a common/remembered "(payment) point of contact" that isn't necessarily a registrant/attendee
* For some events only the primary registrant/point of contact should be emailed - don't gather email for guests but names are needed for name tags, guests are not Contacts or Leads
* Get a name for each table (not necessarily the primary registrant's company)
* Print name tags for primary registrants and guests
* Print table name sign/placards
* Discount/comp/sponsor codes

**Comment by jimhubert** [comment]
Linking this issue with original "Guest Management" issue https://github.com/SFDO-Community-Sprints/Summit-Events-App/issues/30

**Comment by rdblake21** [comment]
Salesforce Sprint Feb 10th – 11th 2021
Summit Event Guest Registration Breakout – Day 1 Feb 10th 2021
Attendees:  Mike Walter, Thad Dahlberg, Sue Kolles
1)	Do guests need to follow contact match rules?  What data is needed?   How does that work.   Are there options/configuration needed for this?  

•	In the Contact Matching section of the Event page, either create another option for guest configuration or add another option to existing picklists.  
 
![image](https://user-images.githubusercontent.com/60475518/107650123-c645bd80-6c43-11eb-988c-a1bd73c08cf9.png)

•	Minimal fields needed for contact matching and contact creation is first name, last name and email address.   If an event is configured to allow for guests and NOT require an email address for each guest, then the Contact Matching No Match Behavior MUST be set to Skip Creating Contact.

2)	What fields are required / not required for guest registration?
•	First Name and Last Name will always be required for every guest.
•	In the Options section of the Event page, add another option for guest email address requirement (see below).  Allow configuration to ‘ask’, ‘not ask’ and ‘ask and require’.    Also, for existing field options, add another value in picklists for guest variation, ‘Ask and require but not for Guests’. 
![image](https://user-images.githubusercontent.com/60475518/107650159-cf368f00-6c43-11eb-8c62-90f6962bcb57.png)

 
3)	Should we ask registrants to input the number of guests that should be included in the registration?  
•	Yes.  We should allow registrant to enter the actual number of guests but allow them to add fewer number of guests and finish registration.   We could potentially create a rollup summary used for reporting to show registrations that don’t have all the guest info yet.
•	We should also ask registrant if they will be attending or if they are just registering others.
•	If not all guest information is entered at time of initial registration, we discussed options to obtain guest information at a later time.
i.	Create event portal to allow registrants to create an account and come in and manage their registrations for all events they are attending.   Since this requires a Community license, this wouldn’t be an option for Summit events.
ii.	We discussed creating a case for this registration for event coordinator to follow-up with registrant to obtain additional information.  After obtaining additional info from registrant, the event coordinator would click the down arrow/carrot next to ‘Hosted Registrants’ and choose ‘New’ to add more guests under host.
iii.	Another option was to include event team’s contact information in email confirmation, so registrant knows who to follow-up with additional information.
4)	If guests are included in the registration, should they receive an email confirmation when the registration is submitted?
•	Thad is recommending NOT to email guests.  Confirmation should only go to Host registrant.  There could be a legal compliance issue sending emails to guests.   This needs to be researched.
5)	What would happen if someone cancels and they had guests, are the guests cancelled too?   
•	On cancellation page, we need to ask if all guests or just host is cancelling.   Could we potentially list all guests and allow them to pick who cannot attend?
6)	How do we configure the optional questions (1-5) for guests?   We need to discuss this more. 
•	Questions like ‘Do you have a question for the speaker’ should be optional
•	For events with food service, attendees need to choose dinner option(s), then those questions would be required for each guest.
 
![image](https://user-images.githubusercontent.com/60475518/107650196-d5c50680-6c43-11eb-8383-987a7e6b75f2.png)


7)	For guest registration configuration, Thad wants to combine the various guest registration options in same section.   Currently ‘Display Guest Registration’ and Max Number of guests are in two different sections.  Also, Thad didn’t like the wording of the guest options as they were confusing.   Maybe use a different word than host?  Sometimes admins will register on behalf of others and really isn’t the host.   
8)	Parking Lot item:  How to display host name rather than the SF generated name as host.   Also, for registrations, how to show registrants name rather than SF generated names, so it’s more user friendly?
9)	Campaign generated Event  How to handle those who decline.   Thad suggested we have have link to register (I’m coming) and a link to update campaign member (I’m not coming) with status = Decline that comes from SFMC.

**Comment by rdblake21** [comment]
Notes from a Mike and Jim Working Session

- Guest registration fields need to be configurable by event.   Each field should have an option to ask, ask/required or not ask.  These fields need to be labeled clearly and could include: 

a. Email address 
b. Relationship to host (new field)
c. Relationship to Institution
d. Preferred Class Year
e. Dietary Restriction (new field)
f. Menu Option (customizable pick list, new field) 
g. Customizable fields (existing Question fields)

- Requirement Question Options
-- I'm guessing this is just a prototype issue, but I like the idea of managing the questions via the picklist options on the bottom.  The only additional consideration would be for fields like First Name, Last Name and Email address that are always required for a Registration and how to make Email not required perhaps.

![Guest Reg Fields](https://user-images.githubusercontent.com/60475518/120865332-74f36e00-c553-11eb-817b-95c24a72e1d2.png)

- If guests are allowed, there should be a field asking if the registrant would like to bring a guest on the first page.  If yes, the registrant navigates to Guest Registration page, if no, the registrant navigates to the Confirmation page skipping the Guest Registration Page.  St. Thomas UA requested a number field and validation, but I like Jim's idea of removing any complexity there and simply ask the question to move to the next appropriate page.  I know there are fields on the backend used to limit the number of guest registrations that can be created, but I believe there is no validation on it in the prototype.

- This may also be a prototype issue, but the button on the bottom should be Next as opposed to Register on the first page.

![Guest Register and Next](https://user-images.githubusercontent.com/60475518/120865374-8a689800-c553-11eb-9f52-58adf078db15.png)


- Please change the language on the + Add a guest button to read "Register Guest" or "Submit Guest".  It seems easy to not add someone or question if that's been done.

![Guest Add Guest](https://user-images.githubusercontent.com/60475518/120865525-d1ef2400-c553-11eb-9b2c-c9fa051c6720.png)

- Again, more of a prototype feedback, add a header to the Registered Guest records section like Registered Guest(s) and add Labels to the data under each guest record.  Also carry through the template from previous pages.

![Guest Layout](https://user-images.githubusercontent.com/60475518/120865550-dca9b900-c553-11eb-8f56-c9be496ea0f5.png)

- Another prototype issue, I would prefer the forward actions on the right.  Also open it up to the group if arrows are better and more universal than Next and Previous.

![Guest Next and Previous](https://user-images.githubusercontent.com/60475518/120865568-e8957b00-c553-11eb-9e61-ee32bcd92eba.png)
![Guest Next and Previous2](https://user-images.githubusercontent.com/60475518/120865592-f3501000-c553-11eb-8502-c8ab859c9d6f.png)

- The UA team requested a summary page that will show all details entered so the registrant can review and potentially go back and fix before officially submitting the registration.  I would agree on a summary page, but believe providing the high-level details such as names being more impactful.  I would argue, I could potentially see the details on the previous page and this page 
is confirm I didn't miss adding the guest altogether.  

![Guest Submit Page](https://user-images.githubusercontent.com/60475518/120865684-21355480-c554-11eb-949a-a48bf187cb3a.png)

- The UA team also brought up email confirmations being configurable with guest details displaying.  Jim and I discussed this and think this could be part of a larger Email discussion and probably less of an immediate need.  As I mentioned to Jim, UA is managing two events landing in Summit Events today with guests and are not trying to send out emails.

- On the backend, I think the Host Registration Lookup is working well in Production with our Qualtrics survey and seems to be identical in function in the prototype.  I did not look into the Guest Host Status functionality and how that might present itself on the registration page.  We are not offering this option in Qualtrics today.

![Guest List View](https://user-images.githubusercontent.com/60475518/120865701-2b575300-c554-11eb-8ee1-8f80d15f166b.png)

**Comment by rdblake21** [comment]
Meeting Notes:

* Requirement Question Options
** Remove the multiselect in the guest section and leverage the standard field options adding additional values that control what is asked and what is required
** **Best path** - utilize the additional question record functionality and do a Guest Question vs an Additional Question
* Guests Allowed? If so how many?
** Need to introduce that you're allowing guests.
*** Would a "Path" show reflect progress and how many pages there are in the registration?
*** (may be another iteration) On initial page ask the question "Are you bringing any Guests?", If "Yes", show the Guest Page, If "No", Go to the next appropriate page.
* Limitation Enforcement
** Allow for a limit to the number of guests an individual can register. Max set on backend should be enforced on front end
** Need to have some standard language around the limit to the number of guests in a validation error "You've reached maximum number of guests"
** When considering a payment aspect, need to capture HOW MANY GUEST in a numerical value before names are capture.  Then show blocks for each guest to be completed OR validate that the number indicated is what was entered.
* Guest Registration page
** Header to highlight who is registered and going to be counted
** Label input for header for the Admin/User to control
* Submit Page
** Do a summary of the Registration of who is registered from the previous Guest Registration page
