### ISSUE TITLE
Facing issues on assigning Summit Events Registrant permission set to Guest User

### ISSUE THREAD

**Issue by akkibaddi** [SFDO-Community/Summit-Events-App#240]
Hi Team facing this below issue up on assigning "Summit Events Registrant" Permission set to a Guest user as mentioned in setting up after installation article. 

I looked in to Permission set, looks like no Apps are assigned in there not sure if its our developer org or its a broader issue in general. I am guessing it's a general issue as I tried creating new site as well instead of our existing sites.

"Please fix the following:

Can't complete this operation because it would exceed the number of apps allowed by the user license."

**Comment by tcdahlberg** [comment]
Hi @akkibaddi,

The "Summit Events Registrant" permission set does not have access to the application by design. Guest users can't log in to Salesforce so they couldn't see the app to begin with. Guest users do have selective access to objects, fields, api controllers, and pages that make the front end registration possible. 

There is another permission set, "Summit Events Admin" that gives full access to the Salesforce application for admin users that can be applied to users you wish to create and run events. You can also clone the admin permission set to create selective views for different use cases within your org.

I am not sure why your are getting the error: "Can't complete this operation because it would exceed the number of apps allowed by the user license." Perhaps someone with more licensing experience than I could chime in on this one. @rdblake21, @jimhubert, @walt0019 any ideas?

**Comment by rdblake21** [comment]
I don't believe this is with a specific licenses other than the Guest User license.

@akkibaddi, do you have the most updated permission set that had permissions removed based on Spring '21?  Also, are you using a Guest User that is being used elsewhere or is this a new Guest User?

**Comment by akkibaddi** [comment]
Hi @rdblake21 facing this in both new site as well as existing one. I believe i am using the latest one, as i cloned the latest commit.

**Comment by akkibaddi** [comment]
fyi i am facing the same issue with some empty permission set in my sand box so i guess this is not related to this package and our org issue. Created a support ticket, will keep posted in here on what i hear back incase any one else face this in future.

Thanks!

**Comment by akkibaddi** [comment]
Heard back from Support with this below response

"Upon checking, the guest user profile has two assigned apps which put it into an invalid state. The only app that should be assigned to the guest user is the standard platform app. By editing the assigned apps, to standard platform app only, the permission set should be able to be assigned to guest user."

For some reason up on creating new Guest Users or for Existing Guest User there two App's assigned (HEDA lightning) and Standard Platform, not sure if its replicable in other orgs or is it just our org thing but some thing to be cautious of. I clicked edit and selected one and saved looks like that removed HEDA one and i am able to assign permission set. 


![image](https://user-images.githubusercontent.com/28792957/102148524-9db76800-3e3a-11eb-8e6f-49df70e2d8eb.png)
