### ISSUE TITLE
Event Instance Start and End Times are incorrectly displayed in the Community

### ISSUE THREAD

**Issue by jacebryan** [SFDO-Community/Summit-Events-App#9]
I created an Instance of an Event with the following Start Date/Time and End Date/Time values:

- Start Date/Time: 4/6/2020, 10:00 AM
- End Date/Time: 4/6/2020, 2:00 PM

When I view the event from the Community Base URL I see the following:

- April 6, 2020, 5:00 PM - 9:00 PM

This seems to be related to the fact that Salesforce stores Timezones in GMT time.

Have you considered how to convert the date/time to the specified time zone of the community guest user? 

For example: 

During DST Pacific Time (PDT) is 7 hours behind Greenwich Mean Time (GMT-7). After the Summer months Pacific Time is shifted back by 1 hour to US Pacific Standard Time (PST) or (GMT-8). Pacific Standard Time (PST) is 8 hours behind Greenwich Mean Time (GMT-8).

https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/apex_methods_system_datetime.htm

**Comment by tcdahlberg** [comment]
Yup. That's an issue. I convert to Central Time because that is where I am. It should be generalized either to look for org settings and then adjust or have it in the custom settings for the application. There is a method in the USTEventShared class called adjustForCenteralTime that should be refactored to achieve this.
